theme: jekyll-theme-cayman
title: Welcome to Samsung Open Source Group SOSCON Web Pages
description: Feel free to bookmark. This gives a brief rundown of the Open Source Groups work on IoT Privacy using the Mozilla WoT framework
